# Configuration parameters are documented here:
# https://resilience4j.readme.io/docs/circuitbreaker#create-and-configure-a-circuitbreaker
resilience4j.circuitbreaker:
  instances:
    mycircuitbreaker:
      slowCallDurationThreshold: '500ms'
      permittedNumberOfCallsInHalfOpenState: 1
      waitDurationInOpenState: '5s'

      # Sliding Window
      slidingWindowType: 'COUNT_BASED'
      slidingWindowSize: 1
      minimumNumberOfCalls: 1
