logging.level.com.github.tomboyo: 'TRACE'

spring.cloud:
  function:
    definition: 'clock;request'
  stream.bindings:
    clock-out-0:
      destination: 'clock'
      group: 'group-0'
    request-in-0:
      destination: 'clock'
      group: 'group-0'